# Module debugging
#replacements = "github.com/schnerring/hugo-mod-json-resume -> ../../hugo-mod-json-resume"
[hugoVersion]
  extended = true
  min = "0.84.0"
[[module.mounts]]
  source = "node_modules/simple-icons/icons"
  target = "assets/simple-icons"
[[mounts]]
  source = "assets"
  target = "assets"
[[mounts]]
  source = "layouts"
  target = "layouts"
[[mounts]]
  source = "static"
  target = "static"
[[mounts]]
  source = "node_modules/prismjs"
  target = "assets/prismjs"
[[mounts]]
  source = "node_modules/prism-themes/themes"
  target = "assets/prism-themes"
[[mounts]]
  source = "node_modules/@tabler/icons/icons"
  target = "assets/tabler-icons"